NAME                                                                             ROLE                                                                                  AGE
capi-kubeadm-control-plane-system-capi-kubeadm-control-plane-proxy-rolebinding   ClusterRole/capi-kubeadm-control-plane-system-capi-kubeadm-control-plane-proxy-role   10m
