apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-03-02T14:15:57Z"
  labels:
    cluster.x-k8s.io/provider: control-plane-kubeadm
    clusterctl.cluster.x-k8s.io: ""
    control-plane: controller-manager
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:cluster.x-k8s.io/provider: {}
          f:clusterctl.cluster.x-k8s.io: {}
          f:control-plane: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":8443,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:cluster.x-k8s.io/provider: {}
          f:control-plane: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: clusterctl
    operation: Update
    time: "2021-03-02T14:15:57Z"
  name: capi-kubeadm-control-plane-controller-manager-metrics-service
  namespace: capi-kubeadm-control-plane-system
  resourceVersion: "1105"
  uid: 417df701-4d00-4903-b8ef-49fe9beeca8a
spec:
  clusterIP: 10.96.130.21
  clusterIPs:
  - 10.96.130.21
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    cluster.x-k8s.io/provider: control-plane-kubeadm
    control-plane: controller-manager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
