apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: capi-kubeadm-control-plane-controller-manager-metrics-service
  namespace: {{ include "resource.default.namespace" . }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    {{- include "labels.selector" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
