apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      {{- include "labels.selector" . | nindent 6 }}
  template:
    metadata:
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
      labels:
        control-plane: controller-manager
        {{- include "labels.common" . | nindent 8 }}
    spec:
      containers:
      - args:
        - --metrics-bind-addr=0.0.0.0:{{ .Values.ports.metrics }}
        - --watch-filter={{ .Values.watchfilter }}
        - --webhook-port={{ .Values.ports.webhook }}
        command:
        - /manager
        image: "{{ .Values.registry.domain }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        livenessProbe:
          tcpSocket:
            host: ""
            port: healthz
        readinessProbe:
          tcpSocket:
            host: ""
            port: healthz
        imagePullPolicy: IfNotPresent
        name: manager
        ports:
          - containerPort: {{ .Values.ports.healthz }}
            name: healthz
            protocol: TCP
          - containerPort: {{ .Values.ports.metrics }}
            name: metrics
            protocol: TCP
          - containerPort: {{ .Values.ports.webhook }}
            name: webhook
            protocol: TCP
        volumeMounts:
          - mountPath: /tmp/k8s-webhook-server/serving-certs
            name: cert
            readOnly: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      serviceAccountName: {{ include "resource.default.name" . }}
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: {{ include "resource.default.name" . }}-cert
