name: cluster-api

registry:
  domain: quay.io

image:
  name: giantswarm/kubeadm-control-plane-controller
  tag: 98fc14614970fe9d4542cb6173061290b3e765db

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

watchfilter: capi
