name: cluster-api-control-plane

registry:
  domain: quay.io

image:
  name: giantswarm/kubeadm-control-plane-controller
  tag: v0.4.1

ports:
  healthz: 9440
  metrics: 8080
  webhook: 9443

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

watchfilter: capi
