name: cluster-api
image:
  name: giantswarm/kubeadm-control-plane-controller
  tag: 815685c3d03ac5ca7b6eed6c3a3e3aafd0b96ad9
rbacproxy:
  image:
    name: giantswarm/kube-rbac-proxy
    tag: v0.4.1

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
