name: cluster-api
image:
  registry: quay.io
  name: giantswarm/kubeadm-control-plane-controller
  tag: 45c3a9e4e52738863d5290342c47b2e5cc7e8861
rbacproxy:
  image:
    name: giantswarm/kube-rbac-proxy
    tag: v0.4.1

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
