name: cluster-api
image:
  registry: quay.io
  name: giantswarm/kubeadm-control-plane-controller
  tag: 1f96eea1165d6b356b3a1658eb4e3c7ddaec33b8

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
