name: cluster-api
image:
  name: giantswarm/kubeadm-control-plane-controller
  tag: v0.3.22-gs3

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

watchfilter: capi

registry:
  domain: docker.io

ports:
  metrics: 8080
  webhook: 9443

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
