name: cluster-api

registry:
  domain: quay.io

image:
  name: giantswarm/kubeadm-control-plane-controller
  tag: fa3378e532147820227c7b7a887d9e7ab54fc2ff

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

watchfilter: capi
